/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./character.glb -t --transform -s -k
*/

import * as THREE from "three";
import React, { forwardRef, useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { AnimationClip, Group } from "three";
import { mergeRefs } from "react-merge-refs";

type GLTFResult = GLTF & {
  nodes: {
    glassesRound: THREE.Mesh;
    characterMedium: THREE.SkinnedMesh;
    LeftFootCtrl: THREE.Bone;
    RightFootCtrl: THREE.Bone;
    HipsCtrl: THREE.Bone;
  };
  materials: {
    ["Blue 3"]: THREE.MeshStandardMaterial;
    skin: THREE.MeshStandardMaterial;
  };
  animations: GLTFActions[];
};

export type ActionName = "Interact_standing" | "Wave" | "Idle" | "Run" | "Walk";
type GLTFActions = AnimationClip & Record<ActionName, THREE.AnimationAction>;

export const Model = forwardRef<
  Group,
  JSX.IntrinsicElements["group"] & {
    action: ActionName;
    fade: number | Record<ActionName, number>;
  }
>(({ fade, action, ...props }, ref) => {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/character-transformed.glb"
  ) as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);

  useEffect(() => {
    const f = typeof fade === "number" ? fade : fade[action];
    actions[action]
      ?.reset()
      .setEffectiveTimeScale(1)
      .setEffectiveWeight(1)
      .fadeIn(f)
      .play();
    return () => {
      actions[action]?.fadeOut(f);
    };
  }, [action, actions, fade]);

  return (
    <group ref={mergeRefs([ref, group])} {...props} dispose={null}>
      <group name="Scene">
        <group name="Root">
          <primitive object={nodes.LeftFootCtrl} />
          <primitive object={nodes.RightFootCtrl} />
          <primitive object={nodes.HipsCtrl} />
          <skinnedMesh
            name="characterMedium"
            geometry={nodes.characterMedium.geometry}
            material={materials.skin}
            skeleton={nodes.characterMedium.skeleton}
            castShadow
            receiveShadow
          />
        </group>
      </group>
    </group>
  );
});

useGLTF.preload("/character-transformed.glb");
