use enum_iterator::IntoEnumIterator;

#[derive(Debug, Clone, IntoEnumIterator)]
pub enum BlockTexture {
    BrickGrey,
    BrickRed,
    CactusInside,
    CactusSide,
    CactusTop,
    CottonBlue,
    CottonGreen,
    CottonRed,
    CottonTan,
    Dirt,
    DirtGrass,
    DirtSand,
    DirtSnow,
    FenceStone,
    FenceWood,
    Glass,
    GlassFrame,
    Grass1,
    Grass2,
    Grass3,
    Grass4,
    GrassBrown,
    GrassTan,
    GrassTop,
    GravelDirt,
    GravelStone,
    Greysand,
    Greystone,
    GreystoneRuby,
    GreystoneRubyAlt,
    GreystoneSand,
    Ice,
    Lava,
    Leaves,
    LeavesOrange,
    LeavesOrangeTransparent,
    LeavesTransparent,
    MushroomBrown,
    MushroomRed,
    MushroomTan,
    Oven,
    Redsand,
    Redstone,
    RedstoneEmerald,
    RedstoneEmeraldAlt,
    RedstoneSand,
    Rock,
    RockMoss,
    Sand,
    Snow,
    Stone,
    StoneBrowniron,
    StoneBrownironAlt,
    StoneCoal,
    StoneCoalAlt,
    StoneDiamond,
    StoneDiamondAlt,
    StoneDirt,
    StoneGold,
    StoneGoldAlt,
    StoneGrass,
    StoneIron,
    StoneIronAlt,
    StoneSand,
    StoneSilver,
    StoneSilverAlt,
    StoneSnow,
    Table,
    TrackCorner,
    TrackCornerAlt,
    TrackStraight,
    TrackStraightAlt,
    TrunkBottom,
    TrunkMid,
    TrunkSide,
    TrunkTop,
    TrunkWhiteSide,
    TrunkWhiteTop,
    Water,
    WheatStage1,
    WheatStage2,
    WheatStage3,
    WheatStage4,
    Wood,
    WoodRed,
}

impl BlockTexture {
    pub const SRC: &'static str = "atlas-extruded.png";
    const EXTEND: glam::Vec2 = glam::const_vec2!([1296.0, 1440.0]);
    const TILE_EXTEND: glam::Vec2 = glam::const_vec2!([128.0, 128.0]);
    const EXTRUSION: glam::Vec2 = glam::const_vec2!([8.0, 8.0]);

    pub fn base(&self) -> glam::Vec2 {
        let pos = self.pos();
        (pos.as_vec2() * (Self::TILE_EXTEND + 2.0 * Self::EXTRUSION) + Self::EXTRUSION)
            / Self::EXTEND
    }

    pub fn extend(&self) -> glam::Vec2 {
        Self::TILE_EXTEND / Self::EXTEND
    }

    pub fn tex_coord(&self, local_coord: glam::Vec2) -> glam::Vec2 {
        self.base() + local_coord * self.extend()
    }

    pub const fn pos(&self) -> glam::UVec2 {
        match &*self {
            BlockTexture::BrickGrey => glam::const_uvec2!([4, 2]),
            BlockTexture::BrickRed => glam::const_uvec2!([8, 3]),
            BlockTexture::CactusInside => glam::const_uvec2!([8, 2]),
            BlockTexture::CactusSide => glam::const_uvec2!([8, 1]),
            BlockTexture::CactusTop => glam::const_uvec2!([8, 0]),
            BlockTexture::CottonBlue => glam::const_uvec2!([7, 9]),
            BlockTexture::CottonGreen => glam::const_uvec2!([7, 8]),
            BlockTexture::CottonRed => glam::const_uvec2!([7, 7]),
            BlockTexture::CottonTan => glam::const_uvec2!([7, 6]),
            BlockTexture::Dirt => glam::const_uvec2!([7, 5]),
            BlockTexture::DirtGrass => glam::const_uvec2!([7, 4]),
            BlockTexture::DirtSand => glam::const_uvec2!([7, 3]),
            BlockTexture::DirtSnow => glam::const_uvec2!([7, 2]),
            BlockTexture::FenceStone => glam::const_uvec2!([7, 1]),
            BlockTexture::FenceWood => glam::const_uvec2!([7, 0]),
            BlockTexture::Glass => glam::const_uvec2!([6, 9]),
            BlockTexture::GlassFrame => glam::const_uvec2!([6, 8]),
            BlockTexture::Grass1 => glam::const_uvec2!([6, 7]),
            BlockTexture::Grass2 => glam::const_uvec2!([6, 6]),
            BlockTexture::Grass3 => glam::const_uvec2!([6, 5]),
            BlockTexture::Grass4 => glam::const_uvec2!([6, 4]),
            BlockTexture::GrassBrown => glam::const_uvec2!([6, 3]),
            BlockTexture::GrassTan => glam::const_uvec2!([6, 2]),
            BlockTexture::GrassTop => glam::const_uvec2!([6, 1]),
            BlockTexture::GravelDirt => glam::const_uvec2!([6, 0]),
            BlockTexture::GravelStone => glam::const_uvec2!([5, 9]),
            BlockTexture::Greysand => glam::const_uvec2!([5, 8]),
            BlockTexture::Greystone => glam::const_uvec2!([5, 7]),
            BlockTexture::GreystoneRuby => glam::const_uvec2!([5, 6]),
            BlockTexture::GreystoneRubyAlt => glam::const_uvec2!([5, 5]),
            BlockTexture::GreystoneSand => glam::const_uvec2!([5, 4]),
            BlockTexture::Ice => glam::const_uvec2!([5, 3]),
            BlockTexture::Lava => glam::const_uvec2!([5, 2]),
            BlockTexture::Leaves => glam::const_uvec2!([5, 1]),
            BlockTexture::LeavesOrange => glam::const_uvec2!([5, 0]),
            BlockTexture::LeavesOrangeTransparent => glam::const_uvec2!([4, 9]),
            BlockTexture::LeavesTransparent => glam::const_uvec2!([4, 8]),
            BlockTexture::MushroomBrown => glam::const_uvec2!([4, 7]),
            BlockTexture::MushroomRed => glam::const_uvec2!([4, 6]),
            BlockTexture::MushroomTan => glam::const_uvec2!([4, 5]),
            BlockTexture::Oven => glam::const_uvec2!([4, 4]),
            BlockTexture::Redsand => glam::const_uvec2!([4, 3]),
            BlockTexture::Redstone => glam::const_uvec2!([8, 4]),
            BlockTexture::RedstoneEmerald => glam::const_uvec2!([4, 1]),
            BlockTexture::RedstoneEmeraldAlt => glam::const_uvec2!([4, 0]),
            BlockTexture::RedstoneSand => glam::const_uvec2!([3, 9]),
            BlockTexture::Rock => glam::const_uvec2!([3, 8]),
            BlockTexture::RockMoss => glam::const_uvec2!([3, 7]),
            BlockTexture::Sand => glam::const_uvec2!([3, 6]),
            BlockTexture::Snow => glam::const_uvec2!([3, 5]),
            BlockTexture::Stone => glam::const_uvec2!([3, 4]),
            BlockTexture::StoneBrowniron => glam::const_uvec2!([3, 3]),
            BlockTexture::StoneBrownironAlt => glam::const_uvec2!([3, 2]),
            BlockTexture::StoneCoal => glam::const_uvec2!([3, 1]),
            BlockTexture::StoneCoalAlt => glam::const_uvec2!([3, 0]),
            BlockTexture::StoneDiamond => glam::const_uvec2!([2, 9]),
            BlockTexture::StoneDiamondAlt => glam::const_uvec2!([2, 8]),
            BlockTexture::StoneDirt => glam::const_uvec2!([2, 7]),
            BlockTexture::StoneGold => glam::const_uvec2!([2, 6]),
            BlockTexture::StoneGoldAlt => glam::const_uvec2!([2, 5]),
            BlockTexture::StoneGrass => glam::const_uvec2!([2, 4]),
            BlockTexture::StoneIron => glam::const_uvec2!([2, 3]),
            BlockTexture::StoneIronAlt => glam::const_uvec2!([2, 2]),
            BlockTexture::StoneSand => glam::const_uvec2!([2, 1]),
            BlockTexture::StoneSilver => glam::const_uvec2!([2, 0]),
            BlockTexture::StoneSilverAlt => glam::const_uvec2!([1, 9]),
            BlockTexture::StoneSnow => glam::const_uvec2!([1, 8]),
            BlockTexture::Table => glam::const_uvec2!([1, 7]),
            BlockTexture::TrackCorner => glam::const_uvec2!([1, 6]),
            BlockTexture::TrackCornerAlt => glam::const_uvec2!([1, 5]),
            BlockTexture::TrackStraight => glam::const_uvec2!([1, 4]),
            BlockTexture::TrackStraightAlt => glam::const_uvec2!([1, 3]),
            BlockTexture::TrunkBottom => glam::const_uvec2!([1, 2]),
            BlockTexture::TrunkMid => glam::const_uvec2!([1, 1]),
            BlockTexture::TrunkSide => glam::const_uvec2!([1, 0]),
            BlockTexture::TrunkTop => glam::const_uvec2!([0, 9]),
            BlockTexture::TrunkWhiteSide => glam::const_uvec2!([0, 8]),
            BlockTexture::TrunkWhiteTop => glam::const_uvec2!([0, 7]),
            BlockTexture::Water => glam::const_uvec2!([0, 6]),
            BlockTexture::WheatStage1 => glam::const_uvec2!([0, 5]),
            BlockTexture::WheatStage2 => glam::const_uvec2!([0, 4]),
            BlockTexture::WheatStage3 => glam::const_uvec2!([0, 3]),
            BlockTexture::WheatStage4 => glam::const_uvec2!([0, 2]),
            BlockTexture::Wood => glam::const_uvec2!([0, 1]),
            BlockTexture::WoodRed => glam::const_uvec2!([0, 0]),
        }
    }
}
